apiVersion: apps/v1
kind: Deployment
metadata:
  name: gwa-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api
        tier: backend
    spec:
      containers:
        - name: gwa
          image: pmorelli92/go-with-azure:latest
          ports:
            - name: http
              containerPort: 80
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: keepalive
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: keepalive
            image: buildpack-deps:curl
            args:
            - /bin/sh
            - -ec
            - curl http://gwa-service-pmorelli92.cloud.okteto.net/health
          restartPolicy: Never
---
kind: Service
apiVersion: v1
metadata:
  name: gwa-service
spec:
  selector:
    app: api
    tier: backend
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: NodePort
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gwa-ingress
spec:
  rules:
    - host: gwa-service-pmorelli92.cloud.okteto.net
      http:
        paths:
          - path: /
            backend:
              serviceName: gwa-service
              servicePort: 80
